function [fraction, info] = compute_fraction_for_profile(stepInputs, env_profile)
%COMPUTE_FRACTION_FOR_PROFILE Lifetime consumption for a single daily profile.

    if nargout > 1
        [fraction, info] = simulation.lifetime_daily_consumption(env_profile, ...
            stepInputs.Cell_Losses, ...
            stepInputs.duty_cycle, ...
            stepInputs.hours_per_day, ...
            stepInputs.rth_cooling, ...
            stepInputs.heat_capa, ...
            stepInputs.time_hours, ...
            stepInputs.AF_V, ...
            stepInputs.f_t, ...
            stepInputs.Cell_RatedLifetime_h);
    else
        fraction = simulation.lifetime_daily_consumption(env_profile, ...
        stepInputs.Cell_Losses, ...
        stepInputs.duty_cycle, ...
        stepInputs.hours_per_day, ...
        stepInputs.rth_cooling, ...
        stepInputs.heat_capa, ...
        stepInputs.time_hours, ...
        stepInputs.AF_V, ...
        stepInputs.f_t, ...
        stepInputs.Cell_RatedLifetime_h);
    end
end
