function save_summary(folder, caseConfig, search_result)
%SAVE_SUMMARY Persist key lifetime results to MAT/JSON files.

    summary = struct();
    summary.case = search_result.caseConfig;
    summary.start_voltage = search_result.start_voltage;
    summary.parallel_modules = search_result.min_parallel_modules;
    summary.timeline = struct( ...
        'time_years', search_result.timeline.time_years, ...
        'soh_percent', search_result.timeline.soh_percent, ...
        'steady_temps', search_result.timeline.steady_temps, ...
        'achieved_years', search_result.timeline.achieved_years, ...
        'final_soh', search_result.timeline.final_soh, ...
        'success', search_result.timeline.success, ...
        'failure_reason', search_result.timeline.failure_reason);
    summary.mc = search_result.mc;

    save(fullfile(folder, 'lifetime_summary.mat'), 'summary');
end
