function cells = builtin_cell_definitions()
%BUILTIN_CELL_DEFINITIONS Factory for the default cell definitions.

    cells = struct();

    cells.SCH3400 = struct( ...
        'Cell_Type', 'Skelgrid2_Gen1_SCH3400', ...
        'Cell_ResESR10ms_Ohm', 0.17e-3, ...
        'Cell_ResESR1s_Ohm', 0.21e-3, ...
        'Cell_CapRated_F', 3400, ...
        'Cell_VoltRated_V', 3, ...
        'Module_NumCellSeries', 54, ...
        'Module_RatedVoltage_V', 162, ...
        'Module_Name', 'Skelgrid 2.0', ...
        'Cell_HeatCapa_JpK', 35000/54, ...
        'Cell_MaxRatedTemp_degC', 65, ...
        'Cell_RatedLifetime_h', 1500, ...
        'Cell_LowerSOCLimit_pc', 0, ...
        'Cell_RthToCooling_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToCooling_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToCooling_KpW_liquidCooling', 0.17*54/10, ...
        'Cell_RthToEnvironment_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToEnvironment_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToEnvironment_KpW_liquidCooling', 0.17*54/10);

    cells.SCX5000 = struct( ...
        'Cell_Type', 'Skelgrid2_Gen2_SCX5000', ...
        'Cell_ResESR10ms_Ohm', 0.14e-3, ...
        'Cell_ResESR1s_Ohm', 0.2e-3, ...
        'Cell_CapRated_F', 5000, ...
        'Cell_VoltRated_V', 3, ...
        'Module_NumCellSeries', 54, ...
        'Module_RatedVoltage_V', 162, ...
        'Module_Name', 'Skelgrid 2.0', ...
        'Cell_HeatCapa_JpK', 35000/54, ...
        'Cell_MaxRatedTemp_degC', 65, ...
        'Cell_RatedLifetime_h', 1500, ...
        'Cell_LowerSOCLimit_pc', 0, ...
        'Cell_RthToCooling_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToCooling_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToCooling_KpW_liquidCooling', 0.17*54/10, ...
        'Cell_RthToEnvironment_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToEnvironment_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToEnvironment_KpW_liquidCooling', 0.17*54/10);

    cells.Kaifa4000 = struct( ...
        'Cell_Type', 'Skelgrid2_Gen1_Kaifa4000', ...
        'Cell_ResESR10ms_Ohm', 0.24e-3, ...
        'Cell_ResESR1s_Ohm', 0.3e-3, ...
        'Cell_CapRated_F', 4150, ...
        'Cell_VoltRated_V', 3, ...
        'Module_NumCellSeries', 54, ...
        'Module_RatedVoltage_V', 162, ...
        'Module_Name', 'Skelgrid 2.0', ...
        'Cell_HeatCapa_JpK', 35000/54, ...
        'Cell_MaxRatedTemp_degC', 65, ...
        'Cell_RatedLifetime_h', 1500, ...
        'Cell_LowerSOCLimit_pc', 0, ...
        'Cell_RthToCooling_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToCooling_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToCooling_KpW_liquidCooling', 0.17*54/10, ...
        'Cell_RthToEnvironment_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToEnvironment_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToEnvironment_KpW_liquidCooling', 0.17*54/10);

    cells.SCF3400 = struct( ...
        'Cell_Type', 'Skelgrid2_Gen1_SCF3400', ...
        'Cell_ResESR10ms_Ohm', 0.12e-3, ...
        'Cell_ResESR1s_Ohm', 0.14e-3, ...
        'Cell_CapRated_F', 3400, ...
        'Cell_VoltRated_V', 3, ...
        'Module_NumCellSeries', 54, ...
        'Module_RatedVoltage_V', 162, ...
        'Module_Name', 'Skelgrid 2.0', ...
        'Cell_HeatCapa_JpK', 35000/54, ...
        'Cell_MaxRatedTemp_degC', 65, ...
        'Cell_RatedLifetime_h', 1500, ...
        'Cell_LowerSOCLimit_pc', 0, ...
        'Cell_RthToCooling_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToCooling_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToCooling_KpW_liquidCooling', 0.17*54/10, ...
        'Cell_RthToEnvironment_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToEnvironment_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToEnvironment_KpW_liquidCooling', 2);

    cells.GERE = struct( ...
        'Cell_Type', 'GERE_Blinky_GEN1', ...
        'Cell_ResESR10ms_Ohm', 0.14e-3, ...
        'Cell_ResESR1s_Ohm', 0.18e-3, ...
        'Cell_CapRated_F', 3200, ...
        'Cell_VoltRated_V', 2.85, ...
        'Module_NumCellSeries', 6, ...
        'Module_RatedVoltage_V', 51, ...
        'Module_Name', 'GERE Blinky', ...
        'Cell_HeatCapa_JpK', 35000/54, ...
        'Cell_MaxRatedTemp_degC', 65, ...
        'Cell_RatedLifetime_h', 1500, ...
        'Cell_LowerSOCLimit_pc', 0, ...
        'Cell_RthToCooling_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToCooling_KpW_forcedAirCooling', 1.35*54, ...
        'Cell_RthToCooling_KpW_liquidCooling', 1.35*54/10, ...
        'Cell_RthToEnvironment_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToEnvironment_KpW_forcedAirCooling', 1.35*54, ...
        'Cell_RthToEnvironment_KpW_liquidCooling', 1.35*54/10);

    cells.Cell_SCF3400 = struct( ...
        'Cell_Type', 'Gen1_Cell_SCF3400', ...
        'Cell_ResESR10ms_Ohm', 0.12e-3, ...
        'Cell_ResESR1s_Ohm', 0.14e-3, ...
        'Cell_CapRated_F', 3400, ...
        'Cell_VoltRated_V', 3, ...
        'Module_NumCellSeries', 1, ...
        'Module_RatedVoltage_V', 3, ...
        'Module_Name', 'Single Cell', ...
        'Cell_HeatCapa_JpK', 35000/54, ...
        'Cell_MaxRatedTemp_degC', 65, ...
        'Cell_RatedLifetime_h', 1500, ...
        'Cell_LowerSOCLimit_pc', 0, ...
        'Cell_RthToCooling_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToCooling_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToCooling_KpW_liquidCooling', 0.17*54/10, ...
        'Cell_RthToEnvironment_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToEnvironment_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToEnvironment_KpW_liquidCooling', 2);

    cells.Cell_SCA0300EVO = struct( ...
        'Cell_Type', 'Gen1_Cell_SCA0300EVO', ...
        'Cell_ResESR10ms_Ohm', 0.8e-3, ...
        'Cell_ResESR1s_Ohm', 1e-3, ...
        'Cell_CapRated_F', 330, ...
        'Cell_VoltRated_V', 2.85, ...
        'Module_NumCellSeries', 1, ...
        'Module_RatedVoltage_V', 2.85, ...
        'Module_Name', 'Single Cell', ...
        'Cell_HeatCapa_JpK', 35000/54, ...
        'Cell_MaxRatedTemp_degC', 65, ...
        'Cell_RatedLifetime_h', 2500, ...
        'Cell_LowerSOCLimit_pc', 0, ...
        'Cell_RthToCooling_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToCooling_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToCooling_KpW_liquidCooling', 0.17*54/10, ...
        'Cell_RthToEnvironment_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToEnvironment_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToEnvironment_KpW_liquidCooling', 2);

    cells.Cell_SCX0400 = struct( ...
        'Cell_Type', 'Gen2_Cell_SCX0400', ...
        'Cell_ResESR10ms_Ohm', 0.5e-3, ...
        'Cell_ResESR1s_Ohm', 0.6e-3, ...
        'Cell_CapRated_F', 400, ...
        'Cell_VoltRated_V', 3, ...
        'Module_NumCellSeries', 1, ...
        'Module_RatedVoltage_V', 3, ...
        'Module_Name', 'Single Cell', ...
        'Cell_HeatCapa_JpK', 35000/54, ...
        'Cell_MaxRatedTemp_degC', 65, ...
        'Cell_RatedLifetime_h', 2500, ...
        'Cell_LowerSOCLimit_pc', 0, ...
        'Cell_RthToCooling_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToCooling_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToCooling_KpW_liquidCooling', 0.17*54/10, ...
        'Cell_RthToEnvironment_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToEnvironment_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToEnvironment_KpW_liquidCooling', 2);

    cells.Cell_SCX0500 = struct( ...
        'Cell_Type', 'Gen2_Cell_SCX0500', ...
        'Cell_ResESR10ms_Ohm', 1.2e-3, ...
        'Cell_ResESR1s_Ohm', 2.1e-3, ...
        'Cell_CapRated_F', 500, ...
        'Cell_VoltRated_V', 3, ...
        'Module_NumCellSeries', 1, ...
        'Module_RatedVoltage_V', 3, ...
        'Module_Name', 'Single Cell', ...
        'Cell_HeatCapa_JpK', 35000/54, ...
        'Cell_MaxRatedTemp_degC', 65, ...
        'Cell_RatedLifetime_h', 2500, ...
        'Cell_LowerSOCLimit_pc', 0, ...
        'Cell_RthToCooling_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToCooling_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToCooling_KpW_liquidCooling', 0.17*54/10, ...
        'Cell_RthToEnvironment_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToEnvironment_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToEnvironment_KpW_liquidCooling', 2);

    cells.Cell_SCX5000 = struct( ...
        'Cell_Type', 'Gen1_Cell_SCX5000', ...
        'Cell_ResESR10ms_Ohm', 0.12e-3, ...
        'Cell_ResESR1s_Ohm', 0.2e-3, ...
        'Cell_CapRated_F', 5000, ...
        'Cell_VoltRated_V', 3, ...
        'Module_NumCellSeries', 1, ...
        'Module_RatedVoltage_V', 3, ...
        'Module_Name', 'Single Cell', ...
        'Cell_HeatCapa_JpK', 35000/54, ...
        'Cell_MaxRatedTemp_degC', 65, ...
        'Cell_RatedLifetime_h', 1500, ...
        'Cell_LowerSOCLimit_pc', 0, ...
        'Cell_RthToCooling_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToCooling_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToCooling_KpW_liquidCooling', 0.17*54/10, ...
        'Cell_RthToEnvironment_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToEnvironment_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToEnvironment_KpW_liquidCooling', 2);

    cells.Cell_SCX4000 = struct( ...
        'Cell_Type', 'Gen1_Cell_SCX4000', ...
        'Cell_ResESR10ms_Ohm', 0.08e-3, ...
        'Cell_ResESR1s_Ohm', 0.1e-3, ...
        'Cell_CapRated_F', 4000, ...
        'Cell_VoltRated_V', 3, ...
        'Module_NumCellSeries', 1, ...
        'Module_RatedVoltage_V', 3, ...
        'Module_Name', 'Single Cell', ...
        'Cell_HeatCapa_JpK', 35000/54, ...
        'Cell_MaxRatedTemp_degC', 65, ...
        'Cell_RatedLifetime_h', 1500, ...
        'Cell_LowerSOCLimit_pc', 0, ...
        'Cell_RthToCooling_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToCooling_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToCooling_KpW_liquidCooling', 0.17*54/10, ...
        'Cell_RthToEnvironment_KpW_naturalCooling', 1.35*54, ...
        'Cell_RthToEnvironment_KpW_forcedAirCooling', 0.17*54, ...
        'Cell_RthToEnvironment_KpW_liquidCooling', 2);
end
