function analysis = default_analysis()
%DEFAULT_ANALYSIS Provide default analysis settings (e.g., Monte Carlo).

    analysis = struct();
    analysis.ambientMonteCarlo = struct( ...
        'enabled', false, ...
        'enableInDesign', false, ...
        'numTrials', 200, ...
        'daysPerMonth', 30, ...
        'temperatureJitter_99pct_C', 6, ...
        'smoothingHours', 2, ...
        'randomSeed', []);
end
